apiVersion:          batch/v1
kind:                Job
metadata:
  name:              loadgenerator
spec:
  replicas:          5
  template:
    metadata:
      name:          loadgenerator
    spec:
      containers:
      - name:        hey
        image:       quay.io/mhausenblas/loadgenerator:0.2
      restartPolicy: OnFailure
