global:
  scrape_interval:          5s
  evaluation_interval:      5s

scrape_configs:
  - job_name:               'prometheus'
    static_configs:
      - targets:            ['localhost:9090']

  - job_name:               'cadvisor'
    static_configs:
      - targets:            ['cadvisor:8080']

# from https://www.weave.works/blog/aggregating-pod-resource-cpu-memory-usage-arbitrary-labels-prometheus/
  - job_name:               'kubernetes-nodes'
    kubernetes_sd_configs:
      - role:               node
    tls_config:
      insecure_skip_verify: true
    bearer_token_file:      /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - target_label:         __scheme__
      replacement:          https
    - source_labels:        [__meta_kubernetes_node_label_kubernetes_io_hostname]
      target_label:         instance
