global:
  scrape_interval:        5s
  evaluation_interval:    5s

# Based on https://github.com/openshift/origin/blob/master/examples/prometheus/prometheus.yaml

scrape_configs:

- job_name:               'kubernetes-nodes'
  scheme:                 https
  tls_config:
    ca_file:              /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file:      /var/run/secrets/kubernetes.io/serviceaccount/token

  kubernetes_sd_configs:
  - role:                 node

  relabel_configs:
  - action:               labelmap
    regex:                __meta_kubernetes_node_label_(.+)
