global:
  scrape_interval:       5s
  evaluation_interval:   5s

# Based on https://github.com/waynedovey/openshift-prometheus as well as
# https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml
# and had to set `scheme: http` to make it work.

scrape_configs:

- job_name:              'kubernetes-apiservers'
  scheme:                http
  kubernetes_sd_configs:
  - role:                endpoints
    namespaces:
      names:
      - resorcerer

  relabel_configs:
  - action:              labelmap
    regex:               __meta_kubernetes_node_label_(.+)

- job_name:              'kubernetes-pods'
  scheme:                http
  kubernetes_sd_configs:
  - role:                pod
    namespaces:
      names:
      - resorcerer
