
[[constraint]]
  name = "k8s.io/client-go"
  version = "2.0.0"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.2"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.4.0"
